// ---------------------------------------------------------------------------
// Recovery ID handling.
//
// The Recovery ID is a SECRET recovery credential, separate from the public
// Chat ID. It is:
//   - cryptographically random (high entropy, human-readable)
//   - generated by the app — the user NEVER chooses it
//   - NOT derived from the Chat ID
//   - immutable
//   - never publicly searchable, never shown on a profile
//   - shown to the user exactly once, at the end of registration
//
// Format (matches the product spec):  RC-8FQ2-M7KD-XP9A-G3HW-N5LB-Q7CD
//   - prefix "RC-"
//   - 7 groups of 4 characters from an unambiguous 32-char alphabet
//   - 28 random chars x 5 bits = 140 bits of entropy (>= 128 required)
//
// The Recovery ID is never stored in plaintext. Only
//   sha256(normalizedRecoveryId)
// is stored, in user_secrets.recovery_id_hash. A per-user salt is deliberately
// NOT used for the Recovery ID: the password-recovery Edge Function must be
// able to look the row up directly from the hash, and ~140 bits of random
// entropy make an unsalted hash resistant to brute force. (The security
// ANSWER, which is low-entropy and human-chosen, DOES use a per-user salt via
// PBKDF2 — see securityAnswer.js.)
// ---------------------------------------------------------------------------

import { randomBytes } from './hash'

const ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789' // no I, O, 0, 1
const GROUP_LENGTH = 4
const GROUP_COUNT = 7 // 28 chars x log2(32) = 140 bits

const RECOVERY_ID_RE = new RegExp(
  `^RC-([${ALPHABET}]{${GROUP_LENGTH}}-){${GROUP_COUNT - 1}}[${ALPHABET}]{${GROUP_LENGTH}}$`,
)

function randomGroup() {
  const bytes = randomBytes(GROUP_LENGTH)
  let group = ''
  for (const byte of bytes) {
    group += ALPHABET[byte % ALPHABET.length]
  }
  return group
}

/**
 * Generate a new Recovery ID, e.g. "RC-8FQ2-M7KD-XP9A-G3HW-N5LB-Q7CD".
 */
export function generateRecoveryId() {
  const groups = []
  for (let i = 0; i < GROUP_COUNT; i += 1) groups.push(randomGroup())
  return `RC-${groups.join('-')}`
}

/**
 * Normalize a Recovery ID for hashing: trim + uppercase.
 */
export function normalizeRecoveryId(raw) {
  if (typeof raw !== 'string') return ''
  return raw.trim().toUpperCase()
}

/**
 * Validate a Recovery ID's format.
 */
export function isValidRecoveryId(raw) {
  if (typeof raw !== 'string') return false
  return RECOVERY_ID_RE.test(normalizeRecoveryId(raw))
}
